apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yu0s4qrmi-nodejs 
  janus-idp.io/tekton: yu0s4qrmi-nodejs
  backstage.io/kubernetes-id: yu0s4qrmi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yu0s4qrmi-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml